name: Publish to RubyGems.org

on:
  push:
    branches: main
    paths: lib/racecar/version.rb
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: rubygems-publish
    if: github.repository_owner == 'zendesk'
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install --jobs 4
      - uses: rubygems/release-gem@v1
